# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wq/imx6ull-pro/app/iot_gateway

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wq/imx6ull-pro/app/iot_gateway

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wq/imx6ull-pro/app/iot_gateway/CMakeFiles /home/wq/imx6ull-pro/app/iot_gateway//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wq/imx6ull-pro/app/iot_gateway/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mqtt_demo

# Build rule for target.
mqtt_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mqtt_demo
.PHONY : mqtt_demo

# fast build rule for target.
mqtt_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/build
.PHONY : mqtt_demo/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/main.c.s
.PHONY : src/main.c.s

src/net/ble/bluez_dbus.o: src/net/ble/bluez_dbus.c.o
.PHONY : src/net/ble/bluez_dbus.o

# target to build an object file
src/net/ble/bluez_dbus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/net/ble/bluez_dbus.c.o
.PHONY : src/net/ble/bluez_dbus.c.o

src/net/ble/bluez_dbus.i: src/net/ble/bluez_dbus.c.i
.PHONY : src/net/ble/bluez_dbus.i

# target to preprocess a source file
src/net/ble/bluez_dbus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/net/ble/bluez_dbus.c.i
.PHONY : src/net/ble/bluez_dbus.c.i

src/net/ble/bluez_dbus.s: src/net/ble/bluez_dbus.c.s
.PHONY : src/net/ble/bluez_dbus.s

# target to generate assembly for a file
src/net/ble/bluez_dbus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/net/ble/bluez_dbus.c.s
.PHONY : src/net/ble/bluez_dbus.c.s

src/net/mqtt/mqtt_client.o: src/net/mqtt/mqtt_client.c.o
.PHONY : src/net/mqtt/mqtt_client.o

# target to build an object file
src/net/mqtt/mqtt_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/net/mqtt/mqtt_client.c.o
.PHONY : src/net/mqtt/mqtt_client.c.o

src/net/mqtt/mqtt_client.i: src/net/mqtt/mqtt_client.c.i
.PHONY : src/net/mqtt/mqtt_client.i

# target to preprocess a source file
src/net/mqtt/mqtt_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/net/mqtt/mqtt_client.c.i
.PHONY : src/net/mqtt/mqtt_client.c.i

src/net/mqtt/mqtt_client.s: src/net/mqtt/mqtt_client.c.s
.PHONY : src/net/mqtt/mqtt_client.s

# target to generate assembly for a file
src/net/mqtt/mqtt_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/net/mqtt/mqtt_client.c.s
.PHONY : src/net/mqtt/mqtt_client.c.s

src/utils/log.o: src/utils/log.c.o
.PHONY : src/utils/log.o

# target to build an object file
src/utils/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/utils/log.c.o
.PHONY : src/utils/log.c.o

src/utils/log.i: src/utils/log.c.i
.PHONY : src/utils/log.i

# target to preprocess a source file
src/utils/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/utils/log.c.i
.PHONY : src/utils/log.c.i

src/utils/log.s: src/utils/log.c.s
.PHONY : src/utils/log.s

# target to generate assembly for a file
src/utils/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/utils/log.c.s
.PHONY : src/utils/log.c.s

src/utils/msg_bus.o: src/utils/msg_bus.c.o
.PHONY : src/utils/msg_bus.o

# target to build an object file
src/utils/msg_bus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/utils/msg_bus.c.o
.PHONY : src/utils/msg_bus.c.o

src/utils/msg_bus.i: src/utils/msg_bus.c.i
.PHONY : src/utils/msg_bus.i

# target to preprocess a source file
src/utils/msg_bus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/utils/msg_bus.c.i
.PHONY : src/utils/msg_bus.c.i

src/utils/msg_bus.s: src/utils/msg_bus.c.s
.PHONY : src/utils/msg_bus.s

# target to generate assembly for a file
src/utils/msg_bus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mqtt_demo.dir/build.make CMakeFiles/mqtt_demo.dir/src/utils/msg_bus.c.s
.PHONY : src/utils/msg_bus.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... run"
	@echo "... mqtt_demo"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net/ble/bluez_dbus.o"
	@echo "... src/net/ble/bluez_dbus.i"
	@echo "... src/net/ble/bluez_dbus.s"
	@echo "... src/net/mqtt/mqtt_client.o"
	@echo "... src/net/mqtt/mqtt_client.i"
	@echo "... src/net/mqtt/mqtt_client.s"
	@echo "... src/utils/log.o"
	@echo "... src/utils/log.i"
	@echo "... src/utils/log.s"
	@echo "... src/utils/msg_bus.o"
	@echo "... src/utils/msg_bus.i"
	@echo "... src/utils/msg_bus.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

